version: 0.1.0-{build}

skip_tags: false

platform: x64
configuration: Release

clone_folder: C:\totalcmd-zstd

install:
  - set PATH=C:\msys64\mingw64\bin;C:\msys64\usr\bin;%PATH%
  -
  - bash -lc "pacman --needed --noconfirm -Sy pacman-mirrors"
  - bash -lc "pacman --noconfirm -Syyu"
  - bash -lc "pacman --noconfirm -Su zip"

build: off
build_script:
  - git submodule update --init --recursive
  - make
  -
  - mkdir totalcmd-zstd-v0.1.0
  - cp out\totalcmd-zstd.wcx64 totalcmd-zstd-v0.1.0\totalcmd-zstd.wcx64
  - strip --strip-all --remove-section=.comment --remove-section=.note totalcmd-zstd-v0.1.0\totalcmd-zstd.wcx64
  - sed "s/#VERSION#/v0.1.0/" pluginst.inf > totalcmd-zstd-v0.1.0\pluginst.inf
  - zip totalcmd-zstd-v0.1.0.zip totalcmd-zstd-v0.1.0/*

test: off

artifacts:
  - path: totalcmd-zstd-v0.1.0.zip

deploy:
  provider: GitHub
  artifact: totalcmd-zstd-v0.1.0.zip
  auth_token:
    secure: +ojhitnhqsAMTn/yVxUyiAYPT0RAz77+QJcLNVxm98LASuoKZufsBxJYMvt24OjY
  on:
    appveyor_repo_tag: true

notifications:
  - provider: Email
    to: nabijaczleweli@gmail.com
    on_build_status_changed: true
